version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.04
    steps:
      - checkout
      # Whatever you want to do
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
     # - run: npm run start
      
  