version: 2.1
orbs:
  node: circleci/node@5.2.0

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Whatever you want to do
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
          name: Install Dependencies
      - run:
          command: npm start
          name: Run the apllication
      
  