version: 2.1
orbs:
  node: circleci/node@5.1.0
  coveralls: coveralls/coveralls@2.1.0

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Whatever you want to do
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: npm install
      - run: npm test
      - coveralls/upload
       # Run coverage report for Code Climate
      - run:
          name: Setup Code Climate test-reporter
          command: ./cc-test-reporter before-build
          when: always
      - run:
          name: Send coverage report to Code Climate
           # nyc report requires that nyc has already been run,
           # which creates the .nyc_output folder containing necessary data
          command: ./cc-test-reporter after-build -t lcov
          when: always
            # Upload results
      - store_artifacts: # upload test coverage as artifact
          path: ./coverage/lcov.info
          prefix: tests